config/routes.rb
Rails.application.routes.draw do
  resource :session
  resources :passwords, param: :token
  resources :register, only: [:new, :create]
  get "user/profile/:id", to: "user#profile", as: "user_profile"
  post "auth/login", to: "login#login"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "landing#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :session
  delegate :user, to: :session, allow_nil: true
end

app/models/session.rb
class Session < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :sessions, dependent: :destroy

  normalizes :email_address, with: ->(e) { e.strip.downcase }

  validates :name, presence: true, uniqueness: { case_sensitive: false }
  validates :email_address, uniqueness: { case_sensitive: false }
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Authentication
  include JsonWebToken
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  # allow_browser versions: :modern
  before_action :authenticate_request

  private

  def authenticate_request
    token = request.headers["Authorization"]&.split(" ")&.last
    if token.present?
      jwt_decode(token) # Pass the token for decoding
    else
      render json: { error: "Token is missing" }, status: :unauthorized
    end
  rescue JWT::DecodeError => e
    render json: { error: "Invalid token: #{e.message}" }, status: :unauthorized
  end
end

app/controllers/concerns/authentication.rb
module Authentication
  extend ActiveSupport::Concern

  included do
    before_action :require_authentication
    helper_method :authenticated?
  end

  class_methods do
    def allow_unauthenticated_access(**options)
      skip_before_action :require_authentication, **options
    end
  end

  private
    def authenticated?
      resume_session
    end

    def require_authentication
      resume_session || request_authentication
    end


    def resume_session
      Current.session ||= find_session_by_cookie
    end

    def find_session_by_cookie
      Session.find_by(id: cookies.signed[:session_id])
    end


    def request_authentication
      session[:return_to_after_authenticating] = request.url
      redirect_to new_session_path
    end

    def after_authentication_url
      session.delete(:return_to_after_authenticating) || root_url
    end


    def start_new_session_for(user)
      user.sessions.create!(user_agent: request.user_agent, ip_address: request.remote_ip).tap do |session|
        Current.session = session
        cookies.signed.permanent[:session_id] = { value: session.id, httponly: true, same_site: :lax }
      end
    end

    def terminate_session
      Current.session.destroy
      cookies.delete(:session_id)
    end
end

app/controllers/concerns/json_web_token.rb
# frozen_string_literal: true

require "jwt"
module JsonWebToken
  extend ActiveSupport::Concern

  SECRET_KEY = Rails.application.secret_key_base

  def jwt_encode(payload, exp = 7.days.from_now)
    payload[:exp] = exp.to_i
    JWT.encode(payload, SECRET_KEY)
  end

  def jwt_decode(token)
    decoded = JWT.decode(token, SECRET_KEY)[0]
    HashWithIndifferentAccess.new decoded
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  skip_before_action :authenticate_request
  allow_unauthenticated_access

  def index

    current_user = ""

    if authenticated?
      current_user = Current.user.email_address
    end

    @user = User.find_by(email_address: current_user)
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController
  skip_before_action :authenticate_request
  allow_unauthenticated_access
  skip_forgery_protection

  def login
    @user = User.find_by_email_address(params[:email_address])
    if @user&.authenticate(params[:password])
      token = jwt_encode(user_id: @user.id)
      render json: { token: token }, status: :ok
    else
      render json: { error: "unauthorized" }, status: :unauthorized
    end
  end
end

app/controllers/passwords_controller.rb
class PasswordsController < ApplicationController
  skip_before_action :authenticate_request
  allow_unauthenticated_access
  before_action :set_user_by_token, only: %i[ edit update ]

  def new
  end

  def create
    if user = User.find_by(email_address: params[:email_address])
      PasswordsMailer.reset(user).deliver_later
    end

    redirect_to new_session_path, notice: "Password reset instructions sent (if user with that email address exists)."
  end

  def edit
  end

  def update
    if @user.update(params.permit(:password, :password_confirmation))
      redirect_to new_session_path, notice: "Password has been reset."
    else
      redirect_to edit_password_path(params[:token]), alert: "Passwords did not match."
    end
  end

  private

  def set_user_by_token
    @user = User.find_by_password_reset_token!(params[:token])
  rescue ActiveSupport::MessageVerifier::InvalidSignature
    redirect_to new_password_path, alert: "Password reset link is invalid or has expired."
  end
end

app/controllers/register_controller.rb
class RegisterController < ApplicationController
  skip_before_action :authenticate_request
  allow_unauthenticated_access
  skip_forgery_protection

  def new
    @user = User.new
  end

  def create
    @user = User.new(register_params)

    Rails.logger.info("Request format: #{request.format}")

    if @user.save
      respond_to do |format|
        format.json { render json: { "Success": true, "Message": "Account created!" }, status: :created }
        format.html { redirect_to new_session_path }
      end
    else
      respond_to do |format|
        format.json { render json: { "Success": false, "Message": "This account is not available!" }, status: :conflict }
        format.html { render "new", status: :unprocessable_entity }
      end
    end
  end

  private

  def register_params
    params.permit(:name, :email_address, :password)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :authenticate_request
  allow_unauthenticated_access only: %i[ new create ]
  rate_limit to: 10, within: 3.minutes, only: :create, with: -> { redirect_to new_session_url, alert: "Try again later." }

  def new
  end

  def create
    if user = User.authenticate_by(params.permit(:email_address, :password))
      start_new_session_for user
      redirect_to root_path
    else
      redirect_to new_session_path, alert: "Try another email address or password."
    end
  end

  def destroy
    terminate_session
    redirect_to new_session_path
  end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
  skip_before_action :authenticate_request

  def profile
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/login_helper.rb
module LoginHelper
end

app/helpers/register_helper.rb
module RegisterHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/landing/index.erb
<section class="flex flex-col">

  <div class="mt-24 mb-40 lg:mb-96 lg:grid lg:grid-cols-3 lg:mt-0">
    <div>
      <%= image_tag "nutriwiselogo.png", class: "animate-in slide-in-from-top-96 fade-in-0 duration-2s lg:w-56 lg:h-56" %>
      <div class="hidden lg:block">
        <p class="animate-in slide-in-from-left-96 fade-in-0 duration-2s text-mainColor2 font-poppins xl:text-xl 2xl:text-2xl">NutriWise
          is a
          mobile application that scans food to provide detailed
          nutritional
          information and health
          benefits. Designed to combat child stunting, it helps users make informed dietary choices by leveraging
          AI-powered food recognition, real-time data, and user friendly tools to promote better nutrition and healthier
          lives.</p>
        <div class="lg:flex lg:pt-4 lg:pb-4 lg:mt-28">
          <%= link_to "Learn More", new_session_path, class: "animate-in slide-in-from-bottom-96 fade-in-0 duration-2s p-4 text-white bg-mainColor2 rounded-3xl w-60 text-center" %>
        </div>
      </div>
    </div>
    <div class="hidden lg:block lg:col-span-2">
      <div class="animate-in fade-in-0 duration-4s lg:flex lg:flex-row-reverse lg:mt-8 xl:text-2xl">
        <%= link_to "Signup", new_session_url, class: "p-4 text-mainColor2 font-poppins font-bold" %>
        <%= link_to "Contact", new_session_url, class: "p-4 text-mainColor2 font-poppins font-bold" %>
        <%= link_to "Home", new_session_url, class: "p-4 text-mainColor2 font-poppins font-bold" %>
        <%= link_to "About", new_session_url, class: "p-4 text-mainColor2 font-poppins font-bold" %>
      </div>
      <div>
        <div class="animate-in fade-in-0 duration-4s bgImage">
          <!--          <p>This is BG IMAGE</p>-->
        </div>
      </div>
    </div>
  </div>

  <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out rounded-lg bg-mainColor2 mt-20 lg:mt-48">
    <p class="font-poppins p-4 text-white">Di Indonesia, berdasarkan data Asian Development Bank, pada tahun 2022
      persentase
      Prevalence of
      Stunting Among
      Children Under 5 Years of Age di Indonesia sebesar 31,8 persen. Jumlah tersebut, menyebabkan Indonesia berada
      pada
      urutan ke-10 di wilayah Asia Tenggara.</p>
    <p class="font-poppins p-4 text-white text-end">
      <cite>"Jesica Deviana"</cite>
    </p>
  </div>

  <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <%= image_tag "logo2.png" %>
    <p class="font-poppins text-base text-center font-bold">BERSAMA NUTRIWISE, CEGAH STUNTING SEJAK DINI</p>
  </div>

  <hr>

  <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <%= image_tag "logo3.png" %>
    <p class="font-poppins text-base text-center font-bold">DAPATKAN SARAN TERBAIK UNTUK MENCEGAH STUNTING</p>
  </div>

  <hr>

  <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <%= image_tag "logo4.png" %>
    <p class="font-poppins text-base text-center font-bold">SCAN FOTO UNTUK MENEMUKAN INFO GIZI MAKANAN</p>
  </div>

  <hr>

  <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <%= image_tag "logo5.png" %>
    <p class="font-poppins text-base text-center font-bold">AYO MULAI UNTUK MENUJU INDONESIA EMAS</p>
  </div>

  <div class="onViewAnimate animate-in slide-in-from-bottom-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <div class="flex justify-center items-center">
      <%= link_to "Mulai Perjalanan Anda", new_session_path, class: "font-poppins p-4 text-center text-white bg-mainColor2 rounded-xl w-72" %>
    </div>
  </div>
</section>

app/views/landing/index.html.erb
<%# if authenticated? %>
<%#= Current.user.email_address %>
<%# end %>

<section class="flex flex-col">
  <div class="mt-24 mb-40 lg:mb-96 lg:grid lg:grid-cols-3 lg:mt-0">
    <div>
      <%= image_tag "nutriwiselogo.png", class: "animate-in slide-in-from-top-96 fade-in-0 duration-2s lg:w-56 lg:h-56" %>
      <div class="hidden lg:block">
        <p class="animate-in slide-in-from-left-96 fade-in-0 duration-2s text-mainColor2 font-poppins lg:text-lg xl:text-xl 2xl:text-2xl">NutriWise
          is a
          mobile application that scans food to provid
          <detailed></detailed>
          nutritional
          information and health
          benefits. Designed to combat child stunting, it helps users make informed dietary choices by leveraging
          AI-powered food recognition, real-time data, and user friendly tools to promote better nutrition and
          healthier
          lives.
        </p>
        <div class="lg:flex lg:pt-4 lg:pb-4 lg:mt-28">
          <%= link_to "Learn More", new_session_path, class: "animate-in slide-in-from-bottom-96 fade-in-0 duration-2s p-4 transition-all text-white bg-mainColor2 rounded-3xl w-60 text-center hover:scale-110 hover:bg-mainColor1" %>
        </div>
      </div>
    </div>
    <div class="hidden lg:block lg:col-span-2">
      <%= render partial: "shared/navbar", locals: { user: @user } %>
      <div>
        <div class="animate-in fade-in-0 duration-4s bgImage">
          <!--          <p>This is BG IMAGE</p>-->
        </div>
      </div>
    </div>
  </div>

  <div class="flex flex-col lg:grid lg:grid-cols-2 gap-4 mt-20 lg:mt-48">
    <div class="flex flex-col justify-between bg-mainColor2 rounded-lg onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out transition-all hover:bg-mainColor1">
      <p class="font-poppins p-4 text-white">Di Indonesia, berdasarkan data Asian Development Bank, pada tahun 2022
        persentase
        Prevalence of
        Stunting Among
        Children Under 5 Years of Age di Indonesia sebesar 31,8 persen. Jumlah tersebut, menyebabkan Indonesia berada
        pada
        urutan ke-10 di wilayah Asia Tenggara.</p>
      <p class="font-poppins p-4 text-white text-end">
        <cite>"Jesica Deviana"</cite>
      </p>
    </div>
    <div class="flex flex-col justify-between bg-mainColor1 rounded-lg onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out transition-all hover:bg-mainColor2">
      <p class="font-poppins p-4 text-white">Statistik PBB 2020 mencatat, lebih dari 149 juta (22%) balita di seluruh
        dunia mengalami stunting, dimana 6,3 juta merupakan anak usia dini atau balita stunting adalah balita Indonesia.
        Menurut UNICEF, stunting disebabkan anak kekurangan gizi dalam dua tahun usianya, ibu kekurangan nutrisi saat
        kehamilan, dan sanitasi yang buruk.</p>
      <p class="font-poppins p-4 text-white text-end">
        <cite>"PAUDPEDIA"</cite>
      </p>
    </div>
  </div>


  <div class="lg:grid lg:grid-cols-2 gap-4">

    <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
      <%= image_tag "logo2.png" %>
      <p class="font-poppins text-base text-center font-bold lg:text-2xl">BERSAMA NUTRIWISE, CEGAH STUNTING SEJAK
        DINI</p>
    </div>

    <div class="onViewAnimate animate-in slide-in-from-right-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
      <%= image_tag "logo3.png" %>
      <p class="font-poppins text-base text-center font-bold lg:text-2xl">DAPATKAN SARAN TERBAIK UNTUK MENCEGAH
        STUNTING</p>
    </div>

    <div class="onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
      <%= image_tag "logo4.png" %>
      <p class="font-poppins text-base text-center font-bold lg:text-2xl">SCAN FOTO UNTUK MENEMUKAN INFO GIZI
        MAKANAN</p>
    </div>

    <div class="onViewAnimate animate-in slide-in-from-right-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
      <%= image_tag "logo5.png" %>
      <p class="font-poppins text-base text-center font-bold lg:text-2xl">AYO MULAI UNTUK MENUJU INDONESIA EMAS</p>
    </div>

  </div>

  <div class="flex flex-col gap-4 rounded-xl bg-mainColor1 p-4 text-white onViewAnimate animate-in slide-in-from-left-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24 ">
    <h1 class="text-2xl font-bold underline text-center">About Us</h1>
    <p class="font-poppins text-lg text-center">
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. A alias aperiam architecto asperiores at cum, cumque
      dolores explicabo ipsum iure magnam minima nobis non odio perferendis saepe sit suscipit vel?
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus amet beatae consequatur cum deserunt,
      excepturi, magnam officiis quae sit unde voluptatem voluptatum! Alias blanditiis corporis deleniti exercitationem,
      magni molestiae voluptatem?
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Commodi enim exercitationem id impedit labore magnam nam
      perspiciatis quo sunt voluptates. Ab illo iusto odio. Corporis explicabo fuga minima rerum ullam?
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. At dignissimos dolor doloribus eos fugiat iure pariatur!
      Architecto deleniti ea enim, eos facilis ipsam pariatur, praesentium rem sit, tempora veritatis vitae?
      Lorem ipsum dolor sit amet, consectetur adipisicing elit. Animi beatae dolorem eos, incidunt modi nisi optio
      praesentium quo repellat voluptatibus. Atque autem, deleniti eaque eveniet laudantium nobis rem sint vero!
    </p>
  </div>

  <div class="onViewAnimate animate-in slide-in-from-bottom-14 fade-in-0 duration-2s ease-in-out mt-16 mb-24">
    <div class="flex justify-center items-center">
      <%= link_to "Mulai Perjalanan Anda", new_session_path, class: "font-poppins p-4 text-center text-white bg-mainColor2 rounded-xl w-72 transition-all hover:bg-mainColor1" %>
    </div>
  </div>


</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= content_for(:title) || "Nutri Wise" %></title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="mobile-web-app-capable" content="yes">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= yield :head %>

  <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
  <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

  <%= favicon_link_tag asset_path('logo2.png') %>
<!--  <link rel="icon" href="/icon.png" type="image/png">-->
<!--  <link rel="icon" href="/icon.svg" type="image/svg+xml">-->
<!--  <link rel="apple-touch-icon" href="/icon.png">-->

  <%# Includes all stylesheet files in app/assets/stylesheets %>
  <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
  <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
  <%= javascript_include_tag "onViewAnimation" %>
</head>

<body class="overflow-x-hidden">
<main class="p-4 h-screen">
  <%= yield %>
</main>
</body>
</html>

app/views/register/new.html.erb
<section class="h-full flex justify-center items-center">
  <div class="md:w-2/3 w-full">
    <% if alert = flash[:alert] %>
      <p class="py-2 px-3 bg-red-50 mb-5 text-red-500 font-medium rounded-lg inline-block" id="alert"><%= alert %></p>
    <% end %>

    <% if notice = flash[:notice] %>
      <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-lg inline-block" id="notice"><%= notice %></p>
    <% end %>

    <h1 class="text-center font-bold text-4xl">Register</h1>

    <%= form_with url: register_index_path, class: "contents" do |form| %>
      <div class="my-5">
        <%= form.text_field :name, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your name", value: params[:name], class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.email_field :email_address, required: true, autofocus: true, autocomplete: "username", placeholder: "Enter your email address", value: params[:email_address], class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="my-5">
        <%= form.password_field :password, required: true, autocomplete: "current-password", placeholder: "Enter your password", maxlength: 72, class: "block shadow rounded-md border border-gray-400 outline-none px-3 py-2 mt-2 w-full" %>
      </div>

      <div class="col-span-6 sm:flex sm:items-center sm:gap-4">
        <div class="inline text-center">
          <%= form.submit "Register", class: "rounded-lg py-3 px-5 bg-blue-600 text-white inline-block font-medium cursor-pointer" %>
        </div>

        <div class="mt-4 text-sm text-gray-500 sm:mt-0">
          <%= link_to "Have an account ?", new_session_path, class: "text-gray-700 underline" %>
        </div>
        <div class="mt-4 text-sm text-gray-500 sm:mt-0">
          <%= link_to "Forgot password?", new_password_path, class: "text-gray-700 underline" %>
        </div>
      </div>
    <% end %>
  </div>
</section>

app/views/shared/_navbar.html.erb
<div class="flex justify-start gap-4 items-center animate-in fade-in-0 duration-4s lg:flex lg:flex-row-reverse lg:mt-8 lg:text-lg xl:text-2xl round">
  <% if authenticated? %>
    <%= link_to user_profile_path(user) do %>
      <%= image_tag "anonymous.jpg", class: "border border-black border-solid rounded-full max-w-12 transition-all hover:scale-105" %>
    <% end %>
  <% else %>
    <%= link_to "Sign-in", new_session_path, class: "p-4 text-mainColor2 font-poppins font-bold transition-all hover:scale-125 hover:text-mainColor1" %>
  <% end %>
  <%= link_to "Contact", new_session_path, class: "p-4 text-mainColor2 font-poppins font-bold transition-all hover:scale-125 hover:text-mainColor1" %>
  <%= link_to "About", new_session_path, class: "p-4 text-mainColor2 font-poppins font-bold transition-all hover:scale-125 hover:text-mainColor1" %>
  <%= link_to "Home", new_session_path, class: "p-4 text-mainColor2 font-poppins font-bold transition-all hover:scale-125 hover:text-mainColor1" %>
</div>

app/views/user/profile.html.erb
<section class="flex flex-col gap-4 shadow-mainColor2 shadow-inner rounded-3xl p-4">
  <div class="flex flex-col justify-center items-center gap-4">
    <%= image_tag "anonymous.jpg", class: "rounded-full max-w-32 border border-black border-solid" %>
    <p><%= @user.name %></p>
  </div>

  <div>
    <h1>adasd</h1>
  </div>
</section>